### ISSUE TITLE
Beskrive behov for logisk sjekk

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/ValidateSpellCheckEpub#2]
ValidateSpellCheckEpub

- hva skal den gjøre
- hvordan skal den brukes

**Comment by josteinaj** [comment]
Her må vi ha et møte. Får vi til noe med alle tre i løpet av desember?

**Comment by eliseaas** [comment]
> Her må vi ha et møte. Får vi til noe med alle tre i løpet av desember?

I morgen, fredag (denne uken), tirsdag eller onsdag neste uke?

**Comment by josteinaj** [comment]
Flott. Jeg kalte inn til tirsdag neste uke nå.

**Comment by josteinaj** [comment]
Vi diskuterte og kom fram til krav. Jeg legger dem inn i #1.
